version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'
    networks:
      - intranet

  kratos:
    build:
      context: ./infra/kratos
    env_file: ./.env
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    command: serve -c ./home/ory/kratos.yml --dev --watch-courier
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - intranet

networks:
  intranet:

volumes:
  data:
