version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'
    networks:
      - intranet

  kratos-migrate:
    build:
      context: ./infra/kratos
    depends_on:
      - db
    env_file: ./.env
    command: ['migrate', 'sql', '--read-from-env', '--config', '/home/ory/kratos.yml', '--yes']
    networks:
      - intranet

  kratos:
    build:
      context: ./infra/kratos
    env_file: ./.env
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    command: serve -c ./home/ory/kratos.yml --dev --watch-courier
    volumes:
      - postgres:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
    depends_on:
      - db

networks:
  intranet:

volumes:
  postgres:
    name: orystarter
